CREATE DATABASE task11

USE task11

CREATE TABLE STUDENTS
(
S_ID INT PRIMARY KEY IDENTITY(1,1),
S_NAME VARCHAR(25),
DEPT VARCHAR(25),
YOC VARCHAR(10)
)


INSERT INTO STUDENTS(S_NAME,DEPT,YOC) VALUES
('SELVA','BCA','2023'),('PRAKASH','IT','2021'),('ARUN','CT','2022'),('ARJUN','CSE','2020')
,('VINESH','CSE','2021'),('DIVYA','BCA','2023'),('RANITA','IT','2020'),('YAMINI','CT','2022')
,('HARISHMITHA','BCA','2021'),('HARITA','CSE','2020'),('SHRIKANTH','BCA','2023'),('DARSHAN','BCA','2022')
,('VIKRAM','IT','2021'),('VASANTH','CT','2020'),('HARI','CSE','2023'),('SIVA','IT','2022')
,('KARTHI','CT','2020'),('HEMANTH','IT','2021'),('SHARON','CT','2022'),('HARSHAN','CSE','2023')

SELECT * FROM STUDENTS

-- 1) PIVOT

SELECT YOC,BCA,IT,CT,CSE FROM
(SELECT DEPT,S_ID,YOC FROM STUDENTS) AS TBL1
PIVOT
(COUNT(S_ID) FOR DEPT IN (BCA,IT,CT,CSE)) AS TBL2;

SELECT * FROM STUDENTS

-- 2) UNPIVOT

SELECT DEPT,YOC,S_IDFROM(SELECT YOC, COALESCE(BCA,0) AS BCA ,COALESCE(IT,0) AS IT, COALESCE(CT,0) AS CT, COALESCE(CSE,0) AS CSE FROM STUDENTSPIVOT (SUM (S_ID) FOR DEPT IN(BCA,IT,CT,CSE)) AS PIVOTTABLE)PUNPIVOT(S_ID FOR DEPT IN (BCA,IT,CT,CSE))AS UNPIVOTTABLE