CREATE DATABASE TASK12

--EMPLOYEE TABLE 

CREATE TABLE EMPLOYEE
(
E_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255)
)
-----------------------------------------------

-- CALL_OUTCOME

CREATE TABLE CALL_OUTCOME
(
CALL_ID INT PRIMARY KEY,
OUTCOME_TEXT VARCHAR(128)
)

-----------------------------------------------

-- COUNTRY TABLE

CREATE TABLE COUNTRY
(
COUN_ID INT PRIMARY KEY,
COUNTRY_NAME CHAR(128),
COUNTRY_NAME_ENG CHAR(128),
COUNTRY_CODE CHAR(8)
)

-----------------------------------------------

-- CITY TABLE

CREATE TABLE CITY
(
CITY_ID INT PRIMARY KEY,
CITY_NAME CHAR(128),
LAT DECIMAL(9,6),
LONG DECIMAL(9,6),
COUNTRY_ID INT REFERENCES COUNTRY(COUN_ID)
)

-----------------------------------------------

-- CUSTOMER TABLE

CREATE TABLE CUSTOMER
(
CUS_ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(255),
CITY_ID INT REFERENCES CITY(CITY_ID),
CUSTOMER_ADDRESS VARCHAR(255),
NEXT_CALL_DATE DATE NOT NULL,
TS_INSERTED DATETIME
)

-----------------------------------------------

-- CALL TABLE

CREATE TABLE CALL
(
CALL_ID INT PRIMARY KEY,
EMPLOYEE_ID INT REFERENCES EMPLOYEE(E_ID),
CUSTOMER_ID INT REFERENCES CUSTOMER(CUS_ID),
START_TIME DATETIME,
END_TIME DATETIME NOT NULL,
CALL_OUTCOME_ID INT NOT NULL REFERENCES CALL_OUTCOME(CALL_ID)
)