CREATE DATABASE TASK13

USE TASK13

-- USER TABLE 

CREATE TABLE USERS
(
USER_ID INT PRIMARY KEY,
USER_NAME VARCHAR(16),
PASSWORD VARCHAR(40)
)

-------------------------------------------------------

--FINAID_MAIN TABLE

CREATE TABLE FINAID_MAIN
(
AID_ID INT PRIMARY KEY,
NAME VARCHAR(50),
CATEGORY VARCHAR(15)
)

-------------------------------------------------------

-- USER_FINAID_MAP TABLE

CREATE TABLE USER_FINAID_MAP
(
USER_ID INT REFERENCES USERS(USER_ID),
AID_ID INT REFERENCES FINAID_MAIN(AID_ID),
SEMESTER VARCHAR(7),
YEAR INT,
OFFERED NUMERIC(18,2),
ACCEPTED NUMERIC(18,2)
)

-------------------------------------------------------

-- USER-MAIL TABLE

CREATE TABLE USER_MAIL
(
USER_ID INT REFERENCES USERS(USER_ID),
EMAIL VARCHAR(50) PRIMARY KEY,
DESCRIPTION VARCHAR(50)
)

-------------------------------------------------------

--HOLD-MAIN

CREATE TABLE HOLD_MAIN
(
USER_ID INT REFERENCES USERS(USER_ID),
HOLD_ID INT PRIMARY KEY,
NAME VARCHAR(25),
DESCRIPTION VARCHAR(15)
)

-------------------------------------------------------

--USER_HOLD_MAP TABLE

CREATE TABLE USER_HOLD_MAP
(
USER_ID INT REFERENCES USERS(USER_ID),
HOL_ID INT REFERENCES HOLD_MAIN(HOLD_ID)
)

-------------------------------------------------------

-- USER SALARY

CREATE TABLE USER_SALARY
(
USER_ID INT REFERENCES USERS(USER_ID),
SALARY NUMERIC(18,2)
)

-------------------------------------------------------

-- USER BALANCE

CREATE TABLE USER_BALANCE
(
USER_ID INT REFERENCES USERS(USER_ID),
BALANCE NUMERIC(18,2)
)

-------------------------------------------------------

-- USER_ADDRESS TABLE

CREATE TABLE USER_ADDRESS
(
USER_ID INT REFERENCES USERS(USER_ID),
ADDRESS VARCHAR(80),
APT_NUM VARCHAR(15),
CITY VARCHAR(25),
STATE VARCHAR(2),
ZIP NUMERIC(5,0),
DESCRIPTION VARCHAR(15)
)

-------------------------------------------------------

-- USER_NUMBER TABLE

CREATE TABLE USER_NUMBER
(
USER_ID INT REFERENCES USERS(USER_ID),
NUMBER NUMERIC (15,0),
DESCRIPTION VARCHAR(15)
)

-------------------------------------------------------

-- ROLE TABLE

CREATE TABLE ROLE
(
ROLE_ID INT PRIMARY KEY,
ROLE_NAME VARCHAR(3),
ROLE_FULL_NAME VARCHAR(15)
)

-------------------------------------------------------

-- USER_ROLE

CREATE TABLE USER_ROLE
(
USER_ID INT REFERENCES USERS(USER_ID),
ROLE_ID INT REFERENCES ROLE(ROLE_ID)
)

-------------------------------------------------------

--DEPARTMENT 

CREATE TABLE DEPARTMENT 
(
DEPT_NAME VARCHAR(25) PRIMARY KEY,
BULDING VARCHAR(20),
BUDGET NUMERIC(18,2)
)

-------------------------------------------------------

--COURSE 

CREATE TABLE COURSE
(
CLASS_ID VARCHAR(7) PRIMARY KEY,
NAME VARCHAR(25),
DEPT_NAME VARCHAR(25) REFERENCES DEPARTMENT(DEPT_NAME),
CREDITS NUMERIC(5,0),
DESCRIPTION VARCHAR(8000)
)

-------------------------------------------------------

--TIME_SLOT TABLE

CREATE TABLE TIME_SLOT
(
TIME_SLOT_ID INT PRIMARY KEY,
DAYS VARCHAR(8),
START_TIME DATETIME,
END_TIME DATETIME
)

-------------------------------------------------------

-- SECTION TABLE

CREATE TABLE SECTION 
(
CLASS_ID VARCHAR(7) REFERENCES COURSE(CLASS_ID),
CLASS_NUM INT PRIMARY KEY,
SEMESTER VARCHAR(7),
YEAR INT,
ROOM_NO VARCHAR(6),
TIME_SLOT_ID INT REFERENCES TIME_SLOT(TIME_SLOT_ID),
CAPACITY INT
)

-------------------------------------------------------

-- TAKES TABLE

CREATE TABLE TAKES
(
USER_ID INT REFERENCES USERS(USER_ID),
CLASS_ID VARCHAR(7) REFERENCES COURSE(CLASS_ID),
CLASS_NUM INT REFERENCES SECTION(CLASS_NUM),
SEMESTER VARCHAR(7),
YEAR INT,
GRADE VARCHAR(2)
)

-------------------------------------------------------

--TEACHES TABLE

CREATE TABLE TEACHES 
(
USER_ID INT REFERENCES USERS(USER_ID),
CLASS_ID VARCHAR(7) REFERENCES COURSE(CLASS_ID),
CLASS_NUM INT REFERENCES SECTION(CLASS_NUM),
SEMESTER VARCHAR(7),
YEAR INT
)

-------------------------------------------------------

-- REQUISITE TABLE

CREATE TABLE REQUISITE
(
CLASS_ID VARCHAR(7) REFERENCES COURSE(CLASS_ID),
REQ_ID INT,
TYPE VARCHAR(4)
)

-------------------------------------------------------