CREATE DATABASE task15

USE task15

-- 1) AUTO COMMIT AND AUTO ROLL BACK IS NOTHING BUT A PREDEFINED COMPLETE STATEMENT AND PREDEFINED ERROR SATEMENT

--AUTO COMMIT IS SUCESSFULL COMMAND

CREATE TABLE DEMO
(
ID INT PRIMARY KEY,
NAME VARCHAR(25)
)

--COMMANDS COMPLETED SUCESSFULLY -(AUTO COMMIT)

INSERT INTO DEMO VALUES
(1,'SELVA'),(1,'GANAPATHI')

-- AUTO ROLLBACK (THE STATEMENT WILL WE TERMINATED BCOZ HERE PRIMARY KEY IS VIOLATED)

----------------------------------------------------------------------------------------------

-- 2) Implicit transactions

SET IMPLICIT_TRANSACTIONS ON 
INSERT INTO DEMO VALUES (1,'SELVA'),(2,'GANAPATHI')

SELECT IIF(@@OPTIONS & 2 = 2,'IMPLICIT ON','IMPLICIT OFF') AS ISIMPLICITON

SELECT
	@@TRANCOUNT AS TRANSACTION_COUNT -- RETURNS 1 BECAUSE TRANSACTION IS ACTIVE

COMMIT

SELECT
	@@TRANCOUNT AS AFTER_TRANSACTION_COUNT	--RETURNS 0 BECAUSE TRANSACTION IS COMMITTED

SET IMPLICIT_TRANSACTIONS OFF

-- 3. Explicit transactions
    -- a. Only Commit - insert statement

BEGIN TRAN

INSERT INTO DEMO VALUES (3,'SUBA'),(4,'SURYA')

SELECT
@@TRANCOUNT AS TRANSACTION_COUNT -- RETURNS 1 BECAUSE TRANSACTION IS ACTIVE

COMMIT

SELECT
@@TRANCOUNT AS AFTER_TRANSACTION_COUNT --RETURNS 0 BECAUSE TRANSACTION IS COMMITTED

-- b. Only Rollback - update statement

BEGIN TRAN 

SELECT * FROM DEMO

UPDATE 
	DEMO
SET
	ID=5 WHERE ID=4

SELECT * FROM DEMO -- CHANGES WILL BE APPILIED BUT

ROLLBACK TRAN --THIS WILL ROLL BACK THE TRANSACTION

SELECT * FROM DEMO

-- C. Savepoint - commit update and insert statements, rollback delete statement

BEGIN TRAN
UPDATE 
	DEMO
SET
	NAME='NANDHU' WHERE ID=4
INSERT INTO DEMO VALUES (5,'SURYA')

SAVE TRANSACTION UPDATE_INSERT --UNTILL THIS TRANSACTIONS WILL BE SAVED

DELETE DEMO WHERE ID=2

SELECT * FROM DEMO

ROLLBACK TRAN UPDATE_INSERT

COMMIT

SELECT * FROM DEMO

